library(stringr)
Startup = read.csv(file.choose())
head(Startup)
Startup1 = Startup

#Fix city where possible -- 
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Bangalore / Palo Alto", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Bangalore / San Mateo", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Bangalore/ Bangkok", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Bangalore / SFO", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Bangalore / USA", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "bangalore", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Chennai/ Singapore", repl = "Chennai")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Dallas / Hyderabad", repl = "Hyderabad")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Hyderabad/USA", repl = "Hyderabad")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Gurgaon / SFO", repl = "Gurgaon")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "India / US", repl = "India")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "London", repl = "India")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Mumbai / Global", repl = "Mumbai")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Mumbai / NY", repl = "Mumbai")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Mumbai / UK", repl = "Mumbai")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "New Delhi/ Houston", repl = "New Delhi")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "New Delhi / US", repl = "New Delhi")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "New Delhi / California", repl = "New Delhi")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "New York/ India", repl = "India")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Noida / Singapore", repl = "Noida")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Pune / Dubai", repl = "Pune")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Pune / US", repl = "Pune")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Pune/Seattle", repl = "Pune")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Pune / Singapore", repl = "Pune")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "Seattle / Bangalore", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "SFO / Bangalore", repl = "Bangalore")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "US/India", repl = "India")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "USA/India", repl = "India")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "US", repl = "India")
Startup1$CityLocation <- str_replace(Startup1$CityLocation , pattern = "USA", repl = "India")

head(Startup1)

#Fix industry where possible
Startup1$IndustryVertical <- str_replace(Startup1$IndustryVertical , pattern = "ECommerce", repl = "eCommerce")
Startup1$IndustryVertical <- str_replace(Startup1$IndustryVertical , pattern = "E-Commerce & M-Commerce platform", repl = "eCommerce")
Startup1$IndustryVertical <- str_replace(Startup1$IndustryVertical , pattern = "Ecommerce Marketplace", repl = "Online Marketplace")
